# travelchill/docker-compose.yml

services:
  angular-app:
    build:
      context: ./angularproject
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - spring-boot-app

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile-springboot
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      ORACLE_DB_URL: jdbc:oracle:thin:@oracle-db:1521/PDB2
      ORACLE_DB_USERNAME: PDB2_ADMIN
      ORACLE_DB_PASSWORD: Cong23122k4
      ORACLE_DB_DRIVER: oracle.jdbc.OracleDriver
    volumes:
      - ./uploads:/app/uploads
    #restart: unless-stopped
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe-21c
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: Cong23122k4
      ORACLE_DATABASE: PDB2
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./db-init:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 3m
    restart: unless-stopped
    mem_limit: 2g
    shm_size: 1g

volumes:
  oracle_data: