-- Kết nối đến PDB2
ALTER SESSION SET CONTAINER = PDB2;

-- Tạo user PDB2_ADMIN
CREATE USER PDB2_ADMIN IDENTIFIED BY Cong23122k4;

-- Gán quyền cơ bản
GRANT CONNECT, RESOURCE, DBA TO PDB2_ADMIN;
GRANT UNLIMITED TABLESPACE TO PDB2_ADMIN;

-- Đảm bảo user có thể tạo bảng và thực hiện các thao tác cần thiết
GRANT CREATE SESSION TO PDB2_ADMIN;
GRANT CREATE TABLE TO PDB2_ADMIN;
GRANT CREATE SEQUENCE TO PDB2_ADMIN;

COMMIT;